import Footer from "@/components/Footer";
import Header from "@/components/Header";
import "@/styles/globals.css"
import Providers from "./Providers";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
